'use client';
import { useEffect, useState } from 'react';
import { Github, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';

type Installation = { id: string; accountLogin: string };
type Repository = { id: string; fullName: string; defaultBranch: string | null; private: boolean };
type Branch = { name: string; commitSha: string };

export function ConnectAnalysisForm() {
  const [installations, setInstallations] = useState<Installation[]>([]); const [installationId, setInstallationId] = useState(''); const [repositories, setRepositories] = useState<Repository[]>([]); const [repositoryId, setRepositoryId] = useState(''); const [branches, setBranches] = useState<Branch[]>([]); const [branch, setBranch] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/v1/github/installations').then((r) => r.ok ? r.json() : Promise.reject()).then((d) => { setInstallations(d.installations); if (d.installations[0]) setInstallationId(d.installations[0].id); }).catch(() => setMessage('GitHub installations could not be loaded.')); }, []);
  useEffect(() => { if (!installationId) return; fetch(`/api/v1/github/repositories?installationId=${encodeURIComponent(installationId)}`).then((r) => r.ok ? r.json() : Promise.reject()).then((d) => setRepositories(d.repositories)).catch(() => setMessage('Authorized repositories could not be loaded.')); }, [installationId]);
  useEffect(() => { if (!installationId || !repositoryId) return; fetch(`/api/v1/github/repositories/${repositoryId}/branches?installationId=${encodeURIComponent(installationId)}`).then((r) => r.ok ? r.json() : Promise.reject()).then((d) => { setBranches(d.branches); setBranch(d.branches[0]?.name ?? ''); }).catch(() => setMessage('Branches could not be loaded.')); }, [installationId, repositoryId]);
  async function connect() { const response = await fetch('/api/v1/github/installations/connect', { method: 'POST' }); const data = await response.json(); if (data.url) window.location.assign(data.url); else setMessage(data.message ?? 'GitHub App setup is required.'); }
  async function submit() { const response = await fetch('/api/v1/analyses', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ installationId, repositoryId, branch }) }); const data = await response.json(); if (response.ok) window.location.assign(`/analyses/${data.id}`); else setMessage(data.message ?? 'Unable to queue analysis.'); }
  return <div className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-medium">GitHub installation</span><select className="h-11 w-full rounded-lg border bg-transparent px-3" value={installationId} onChange={(e) => { setInstallationId(e.target.value); setRepositoryId(''); }}><option value="">Select an installation</option>{installations.map((item) => <option key={item.id} value={item.id}>{item.accountLogin}</option>)}</select></label>{!installations.length && <Button type="button" onClick={connect}><Github size={16} />Connect GitHub</Button>}<label className="block"><span className="mb-2 block text-sm font-medium">Repository</span><select disabled={!installationId} className="h-11 w-full rounded-lg border bg-transparent px-3 disabled:opacity-50" value={repositoryId} onChange={(e) => setRepositoryId(e.target.value)}><option value="">Select a repository</option>{repositories.map((item) => <option key={item.id} value={item.id}>{item.fullName}{item.private ? ' (private)' : ''}</option>)}</select></label><label className="block"><span className="mb-2 block text-sm font-medium">Branch</span><select disabled={!repositoryId} className="h-11 w-full rounded-lg border bg-transparent px-3 disabled:opacity-50" value={branch} onChange={(e) => setBranch(e.target.value)}><option value="">Select a branch</option>{branches.map((item) => <option key={item.name} value={item.name}>{item.name}</option>)}</select></label><div className="flex gap-3 rounded-lg bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-800/50 dark:text-slate-400"><LockKeyhole className="shrink-0 text-emerald-500" size={18} /><p>The server revalidates access and resolves the branch to a commit SHA before queuing. No source is downloaded or executed.</p></div>{message && <p role="alert" className="text-sm text-rose-600">{message}</p>}<Button disabled={!installationId || !repositoryId || !branch} onClick={submit}>Start analysis</Button></div>;
}
