-- Phase 1 foundation migration. Generated schema baseline for PostgreSQL.
CREATE TYPE "MembershipRole" AS ENUM ('OWNER', 'MEMBER');
CREATE TYPE "RepositoryProvider" AS ENUM ('GITHUB');
CREATE TYPE "AnalysisStatus" AS ENUM ('DRAFT', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED');
CREATE TYPE "FindingCategory" AS ENUM ('ARCHITECTURE', 'CODE_QUALITY', 'SECURITY', 'PERFORMANCE', 'MAINTAINABILITY', 'TESTING', 'DEPENDENCIES', 'ERROR_HANDLING', 'DOCUMENTATION');
CREATE TYPE "FindingSeverity" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO');
CREATE TYPE "FindingStatus" AS ENUM ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'IGNORED');

CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT, "email" TEXT, "emailVerified" TIMESTAMP(3), "image" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Account" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "refresh_token" TEXT, "access_token" TEXT, "expires_at" INTEGER, "token_type" TEXT, "scope" TEXT, "id_token" TEXT, "session_state" TEXT, CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "sessionToken" TEXT NOT NULL, "userId" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL, "token" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Organization" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "ownerId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Membership" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "MembershipRole" NOT NULL DEFAULT 'MEMBER', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Membership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Repository" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "provider" "RepositoryProvider" NOT NULL, "externalId" TEXT NOT NULL, "name" TEXT NOT NULL, "fullName" TEXT NOT NULL, "defaultBranch" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Repository_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AnalysisRun" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "repositoryId" TEXT NOT NULL, "status" "AnalysisStatus" NOT NULL DEFAULT 'DRAFT', "branch" TEXT, "commitSha" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AnalysisRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AnalysisScore" ("id" TEXT NOT NULL, "analysisRunId" TEXT NOT NULL, "overall" INTEGER NOT NULL, "security" INTEGER NOT NULL, "codeQuality" INTEGER NOT NULL, "maintainability" INTEGER NOT NULL, "testing" INTEGER NOT NULL, "dependencies" INTEGER NOT NULL, "errorHandling" INTEGER NOT NULL, "architecture" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AnalysisScore_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Finding" ("id" TEXT NOT NULL, "analysisRunId" TEXT NOT NULL, "category" "FindingCategory" NOT NULL, "severity" "FindingSeverity" NOT NULL, "status" "FindingStatus" NOT NULL DEFAULT 'OPEN', "ruleId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "confidence" DOUBLE PRECISION, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Finding_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FindingEvidence" ("id" TEXT NOT NULL, "findingId" TEXT NOT NULL, "filePath" TEXT NOT NULL, "startLine" INTEGER, "endLine" INTEGER, "excerpt" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FindingEvidence_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId"); CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken"); CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token"); CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token"); CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug"); CREATE UNIQUE INDEX "Membership_organizationId_userId_key" ON "Membership"("organizationId", "userId"); CREATE UNIQUE INDEX "Repository_organizationId_provider_externalId_key" ON "Repository"("organizationId", "provider", "externalId"); CREATE UNIQUE INDEX "AnalysisScore_analysisRunId_key" ON "AnalysisScore"("analysisRunId"); CREATE INDEX "Finding_analysisRunId_severity_idx" ON "Finding"("analysisRunId", "severity");
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Organization" ADD CONSTRAINT "Organization_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Membership" ADD CONSTRAINT "Membership_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Repository" ADD CONSTRAINT "Repository_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "AnalysisRun" ADD CONSTRAINT "AnalysisRun_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "AnalysisRun" ADD CONSTRAINT "AnalysisRun_repositoryId_fkey" FOREIGN KEY ("repositoryId") REFERENCES "Repository"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "AnalysisScore" ADD CONSTRAINT "AnalysisScore_analysisRunId_fkey" FOREIGN KEY ("analysisRunId") REFERENCES "AnalysisRun"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Finding" ADD CONSTRAINT "Finding_analysisRunId_fkey" FOREIGN KEY ("analysisRunId") REFERENCES "AnalysisRun"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "FindingEvidence" ADD CONSTRAINT "FindingEvidence_findingId_fkey" FOREIGN KEY ("findingId") REFERENCES "Finding"("id") ON DELETE CASCADE ON UPDATE CASCADE;
