import { ArrowUpRight, Plus } from 'lucide-react';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/lib/auth';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { ScoreRing } from '@/components/reports/score-ring';
import { recentAnalyses } from '@/features/reports/fixtures';

export default async function DashboardPage() { const session = await auth(); if (!session?.user) redirect('/sign-in'); return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-cyan-600 dark:text-cyan-400">Personal workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Engineering health, at a glance.</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Your report history will live here once repository analysis is introduced.</p></div><Link href="/analyses/new"><Button><Plus size={16} />New analysis</Button></Link></div><section className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_1.9fr]"><Card className="bg-slate-950 text-white dark:border-slate-800"><CardContent className="flex min-h-64 flex-col justify-between p-6"><p className="text-sm text-slate-400">Latest health score</p><div className="flex items-end justify-between"><div><p className="text-4xl font-semibold">84<span className="text-lg text-slate-500">/100</span></p><p className="mt-2 text-sm text-slate-300">northstar-web · main</p></div><ScoreRing score={84} size="small" /></div><Link href="/analyses/demo-report" className="flex items-center gap-1 text-sm font-medium text-cyan-300 hover:text-cyan-200">View illustrative report <ArrowUpRight size={15} /></Link></CardContent></Card><Card><CardHeader><h2 className="font-semibold">Recent analyses</h2><p className="mt-1 text-sm text-slate-500">Preview data only — analysis is not yet connected.</p></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[460px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3 font-medium">Repository</th><th className="pb-3 font-medium">Score</th><th className="pb-3 font-medium">Status</th><th className="pb-3 text-right font-medium">Updated</th></tr></thead><tbody>{recentAnalyses.map((analysis) => <tr key={analysis.name} className="border-t border-slate-100 dark:border-slate-800"><td className="py-4"><p className="font-medium">{analysis.name}</p><p className="text-xs text-slate-500">{analysis.branch}</p></td><td className="py-4 font-semibold text-cyan-600 dark:text-cyan-400">{analysis.score}</td><td className="py-4"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">{analysis.status}</span></td><td className="py-4 text-right text-slate-500">{analysis.updated}</td></tr>)}</tbody></table></CardContent></Card></section><Card className="mt-5 border-dashed"><CardContent className="p-6"><h2 className="font-semibold">Ready when analysis arrives</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-400">Phase 1 establishes the reporting experience and secure account boundary. Repository connections and deterministic analysis are intentionally deferred.</p></CardContent></Card></div>; }
