import { Plus } from 'lucide-react';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/lib/auth';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { requireWorkspace } from '@/server/authorization';
import { listAnalysisRunsForOrganization } from '@/features/analyses/analysis-run-query.service';

export default async function DashboardPage() { const session = await auth(); if (!session?.user) redirect('/sign-in'); const { organization } = await requireWorkspace(); const analyses = await listAnalysisRunsForOrganization(organization.id); return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-cyan-600 dark:text-cyan-400">Personal workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Engineering health, at a glance.</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Track repository analysis requests from creation through their queued lifecycle.</p></div><Link href="/analyses/new"><Button><Plus size={16} />New analysis</Button></Link></div><section className="mt-8"><Card><CardHeader><h2 className="font-semibold">Recent analyses</h2><p className="mt-1 text-sm text-slate-500">Requests in this workspace. Analysis processing is not active yet.</p></CardHeader><CardContent className="overflow-x-auto">{analyses.length ? <table className="w-full min-w-[520px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3 font-medium">Repository</th><th className="pb-3 font-medium">Branch</th><th className="pb-3 font-medium">Status</th><th className="pb-3 text-right font-medium">Queued</th></tr></thead><tbody>{analyses.map((analysis) => <tr key={analysis.id} className="border-t border-slate-100 dark:border-slate-800"><td className="py-4"><Link href={`/analyses/${analysis.id}`} className="font-medium hover:text-cyan-600">{analysis.repository.fullName}</Link></td><td className="py-4 font-mono text-xs text-slate-500">{analysis.branch}</td><td className="py-4"><span className="rounded-full bg-cyan-50 px-2 py-1 text-xs font-medium text-cyan-700 dark:bg-cyan-950/40 dark:text-cyan-300">{analysis.status}</span></td><td className="py-4 text-right text-slate-500">{(analysis.queuedAt ?? analysis.createdAt).toLocaleString()}</td></tr>)}</tbody></table> : <div className="rounded-lg border border-dashed p-6"><h3 className="font-medium">No analyses yet</h3><p className="mt-1 text-sm text-slate-500">Connect a GitHub repository and create your first queued analysis.</p></div>}</CardContent></Card></section></div>; }
